name: allspots
description: AllSpots (OpenStreetMap + Flutter)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # i18n (internationalisation FR/EN)
  intl: ^0.20.0

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  image_picker: ^1.1.2
  google_sign_in: ^7.2.0
  flutter_google_maps_webservices: ^1.1.1
  google_fonts: ^8.0.1
  http: ^1.6.0

  # Maps + GPS (OSM - gratuit!)
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # State / routing
  flutter_riverpod: ^2.6.1
  go_router: ^17.1.0

  # Ads
  google_mobile_ads: ^7.0.0

  # Storage
  shared_preferences: ^2.2.3

  # Utilitaires
  uuid: ^4.4.0
  collection: ^1.18.0
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon_allspots.png
  min_sdk_android: 21
  remove_alpha_ios: true
